import { NextPage } from "next"
import Head from "next/head"

const Pomofocus: NextPage = () => {

  return (<>
    <Head>
      <title>Sean Pe</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <div className="container flex">

      </div>
    </main>
  </>)

}

export default Pomofocus
