import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import Modal from "~/components/TattooModal";
import { HomeTab } from "~/components/lander/HomeTab";
import { AboutTab } from "~/components/lander/AboutTab";
import { ExperienceTab } from "~/components/lander/ExperienceTab";
import { motion, AnimatePresence } from "framer-motion";

const Home: NextPage = () => {
  const router = useRouter();
  const scanned = router.query.scanned;
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [activeTab, setActiveTab] = useState("home");
  
  useEffect(() => {
    if (scanned) {
      setIsModalOpen(true);
    }
  }, [scanned]);

  const closeModal = () => setIsModalOpen(false);

  return (
    <>
      <Head>
        <title>Sean Pe - Full Stack Developer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#525252] to-[#040404]">
        <div className="relative isolate w-full max-w-7xl mx-auto px-6 pt-14 lg:px-8">
          {/* Background gradients */}
          <div className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
            <div
              className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#33ccff] to-[#00ff99] opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
              style={{
                clipPath:
                  "polygon(0% 0%, 100% 0%, 100% 75%, 75% 75%, 75% 100%, 50% 75%, 0% 75%)",
              }}
            />
            <div
              className="absolute left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#00ff99] to-[#33ccff] opacity-20 sm:w-[72.1875rem]"
              style={{
                clipPath:
                  "polygon(25% 0%, 100% 0%, 100% 100%, 25% 100%, 0% 50%)",
              }}
            />
          </div>

          <div className="flex flex-col items-center justify-center gap-12">
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full max-w-4xl">
              <TabsList className="grid w-full grid-cols-3 bg-transparent p-0">
                <TabsTrigger 
                  value="home" 
                  className="data-[state=active]:bg-[#33ccff] data-[state=active]:text-gray-900 data-[state=active]:shadow-lg data-[state=active]:shadow-[#33ccff]/30 border border-white/20 text-white hover:bg-white/10 transition-all duration-200 rounded-none"
                >
                  Home
                </TabsTrigger>
                <TabsTrigger 
                  value="about" 
                  className="data-[state=active]:bg-[#33ccff] data-[state=active]:text-gray-900 data-[state=active]:shadow-lg data-[state=active]:shadow-[#33ccff]/30 border border-white/20 text-white hover:bg-white/10 transition-all duration-200 rounded-none"
                >
                  About
                </TabsTrigger>
                <TabsTrigger 
                  value="experience" 
                  className="data-[state=active]:bg-[#33ccff] data-[state=active]:text-gray-900 data-[state=active]:shadow-lg data-[state=active]:shadow-[#33ccff]/30 border border-white/20 text-white hover:bg-white/10 transition-all duration-200 rounded-none"
                >
                  Experience
                </TabsTrigger>
              </TabsList>
              
              <TabsContent value="home" className="mt-8">
                <AnimatePresence mode="wait">
                  <motion.div
                    key="home"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <HomeTab setActiveTab={setActiveTab} />
                  </motion.div>
                </AnimatePresence>
              </TabsContent>

              <TabsContent value="about" className="mt-8">
                <AnimatePresence mode="wait">
                  <motion.div
                    key="about"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <AboutTab />
                  </motion.div>
                </AnimatePresence>
              </TabsContent>

              <TabsContent value="experience" className="mt-8">
                <AnimatePresence mode="wait">
                  <motion.div
                    key="experience"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <ExperienceTab />
                  </motion.div>
                </AnimatePresence>
              </TabsContent>
            </Tabs>
          </div>

          {/* Bottom gradients */}
          <div className="absolute inset-x-0 top-[calc(100%-30rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-47rem)]" aria-hidden="true">
            <div
              className="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[-30deg] bg-gradient-to-tr from-[#33ccff] to-[#00ff99] opacity-20 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
              style={{
                clipPath:
                  "polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%, 0% 50%, 50% 0%)",
              }}
            />
            <div
              className="absolute left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[-30deg] bg-gradient-to-tr from-[#00ff99] to-[#33ccff] opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
              style={{
                clipPath:
                  "polygon(0% 0%, 75% 0%, 100% 25%, 100% 100%, 0% 100%)",
              }}
            />
          </div>
        </div>
      </main>
      <Modal show={isModalOpen} onClose={closeModal}>
        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4">QR Code Scanned!</h2>
          <p>You&apos;ve successfully scanned the QR code.</p>
        </div>
      </Modal>
    </>
  );
};

export default Home;

